import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import ts from 'typescript';
const source = await readFile(new URL('../lib/session-codec.ts', import.meta.url), 'utf8');
const code = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ES2022, target: ts.ScriptTarget.ES2022 } }).outputText;
const { encodeSession, decodeSession } = await import('data:text/javascript;base64,' + Buffer.from(code).toString('base64'));
const secret = 'test-only-secret-with-more-than-32-characters';
const user = { email: 'test@example.com', name: 'Test', role: 'admin', password: 'must-not-leak' };
const token = encodeSession(user, secret, 1000);
assert.equal(Buffer.from(token.split('.')[0], 'base64url').toString().includes('password'), false);
assert.equal(Buffer.from(token.split('.')[0], 'base64url').toString().includes('must-not-leak'), false);
assert.deepEqual(decodeSession(token, secret, 2000), { email: user.email, name: user.name, role: user.role });
assert.equal(decodeSession(token, secret, 1000 + 8 * 3600000), null);
assert.equal(decodeSession(token + '.extra', secret, 2000), null);
assert.equal(decodeSession('broken', secret), null);
assert.equal(decodeSession(token, 'another-secret-at-least-32-characters', 2000), null);
assert.equal(decodeSession(token, '', 2000), null);
assert.throws(() => encodeSession(user, 'short'));
console.log('PASS: session data minimization, expiry, malformed input, signature and missing configuration');
